
#ifndef keyboard_h
#define keyboard_h

enum key {
	KEY_CLARINET = 32,
	KEY_ELECTRIC_GUITAR,
	KEY_OBOE,
	KEY_VIOLIN,
	KEY_XYLOPHONE,
	KEY_PIANO,
	KEY_BANJO,
	KEY_HARPISCORD,
	KEY_POPS,
	KEY_DISCO,
	KEY_16BEAT,
	KEY_LATIN,
	KEY_SWING,
	KEY_SLOW_ROCK,
	KEY_MARCH,
	KEY_WALZ,
	KEY_MIN,
	KEY_MAX,
	KEY_SLOW,
	KEY_FAST,
	KEY_STOP,
	KEY_RECORD,
	KEY_PLAY,
	KEY_START
};

#define KEY_OCT_UP KEY_POPS
#define KEY_OCT_DOWN KEY_SWING

#define KEY_FIRST KEY_XYLOPHONE
#define KEY_PREV KEY_PIANO
#define KEY_NEXT KEY_BANJO
#define KEY_LAST KEY_HARPISCORD
#define KEY_DEL KEY_VIOLIN
#define KEY_CLEAR KEY_OBOE

#define KEY_TEMPO_UP KEY_DISCO
#define KEY_TEMPO_DOWN KEY_SLOW_ROCK

#define KEY_MEASURES KEY_LATIN
#define KEY_METRONOME KEY_16BEAT

void keyboard_init(void);
void keyboard_scan(void);

#endif

